# Generated by Django 6.0.2 on 2026-02-23 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='Brief biography and experience')),
                ('photo', models.ImageField(blank=True, upload_to='interviewers/')),
                ('cal_event_type_id', models.CharField(help_text='Cal.com Event Type ID for booking', max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in USD', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the interviewer is available for bookings')),
                ('companies', models.TextField(blank=True, help_text='Comma-separated list of companies worked at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, related_name='interviewers', to='interviewers.interviewsubject')),
                ('technologies', models.ManyToManyField(blank=True, related_name='interviewers', to='interviewers.technology')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
