# Generated by Django 6.0.2 on 2026-02-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviewers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="interviewer",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="interviewers",
                to="interviewers.humanlanguage",
            ),
        ),
    ]
