# Generated by Django 6.0.2 on 2026-02-23 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviewers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_background', models.TextField(help_text="Customer's background and experience level")),
                ('interview_focus', models.TextField(help_text='What the customer wants to be interviewed on')),
                ('target_companies', models.TextField(blank=True, help_text='Companies the customer is targeting (Google, startups, etc.)')),
                ('additional_info', models.TextField(blank=True, help_text='Any additional information from the customer')),
                ('resume', models.FileField(blank=True, help_text="Customer's resume (stored in MinIO)", upload_to='resumes/')),
                ('scheduled_at', models.DateTimeField(help_text='When the interview is scheduled')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of the interview in minutes')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cal_booking_uid', models.CharField(blank=True, help_text='Cal.com booking UID', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='interviewers.interviewer')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
